pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:jagadishprasadp/jenkins.git',
                    credentialsId: '0177e520-2f18-4d84-b111-167da6b0bbeb'
            }
        }
        stage('Verify Python Installation') {
            steps {
                bat 'C:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\python.exe --version'
            }
        }
        stage('Setup Python Virtual Environment') {
            steps {
                bat 'C:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -m venv venv'
            }
        }
        stage('Install Dependencies') {
            steps {
                bat '.\\venv\\Scripts\\pip install -r myblog\\requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                bat 'echo No tests to run currently'
            }
        }
        stage('Start Application') {
            steps {
                bat '.\\venv\\Scripts\\python myblog\\manage.py runserver 0.0.0.0:8000'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        failure {
            echo 'Pipeline failed! Check the logs for more details.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
    }
}
